jobs:
  manual_tag_release:
    name: Manual Tag Release
    secrets: inherit
    uses: praw-dev/.github/.github/workflows/manual_tag_release.yml@main
    with:
      commit: ${{ inputs.commit }}
name: Manual Tag Release
on:
  workflow_dispatch:
    inputs:
      commit:
        description: The commit the version bump occurred
        required: true
permissions:
  contents: write
