version: 2
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
sphinx:
  builder: dirhtml
formats:
  - pdf
  - epub
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
